apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: hetroserve-demo
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: "hetroserve-router"
        metrics_path: /metrics
        static_configs:
          - targets:
              - "hetroserve-router:8080"

      - job_name: "hetroserve-scorer"
        metrics_path: /metrics
        static_configs:
          - targets:
              - "hetroserve-scorer:8080"

      - job_name: "mock-nvidia"
        metrics_path: /metrics
        static_configs:
          - targets:
              - "mock-nvidia:8000"

      - job_name: "mock-tenstorrent"
        metrics_path: /metrics
        static_configs:
          - targets:
              - "mock-tenstorrent:8000"
